[31m[1m2017-11-28T21:05:17+0800 <error> db.js:15 () Êï∞ÊçÆÂ∫ìËøûÊé•Â§±Ë¥• { MongoError: no primary found in replicaset
    at /app/node_modules/mongodb-core/lib/topologies/replset.js:560:28
    at Server.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/replset.js:312:24)
    at Server.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at /app/node_modules/mongodb-core/lib/topologies/server.js:300:14
    at /app/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'MongoError',
  message: 'no primary found in replicaset' }[22m[39m
[31m[1m2017-11-28T21:05:30+0800 <error> db.js:15 () Êï∞ÊçÆÂ∫ìËøûÊé•Â§±Ë¥• { MongoError: no primary found in replicaset
    at /app/node_modules/mongodb-core/lib/topologies/replset.js:560:28
    at Server.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/replset.js:312:24)
    at Server.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at /app/node_modules/mongodb-core/lib/topologies/server.js:300:14
    at /app/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'MongoError',
  message: 'no primary found in replicaset' }[22m[39m
